# Generated by Django 4.2.16 on 2025-05-18 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('problem', models.TextField()),
                ('number', models.CharField(max_length=13)),
                ('status', models.CharField(choices=[('in_progress', 'В роботі'), ('ready', 'Готово'), ('completed', 'Завершено')], default='in_progress', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employeesapp.problem')),
            ],
        ),
    ]
