# Generated by Django 5.0.7 on 2024-08-24 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('problem', models.TextField()),
                ('number', models.CharField(max_length=13)),
                ('status', models.CharField(choices=[('in_progress', 'В роботі'), ('ready', 'Готово'), ('completed', 'Завершено')], default='in_progress', max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
