# Generated by Django 5.0.7 on 2024-08-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0002_rename_problemsmodel_problems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
    ]
