# Generated by Django 5.0.7 on 2024-09-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0003_rename_problems_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employeesapp.problem')),
            ],
        ),
    ]
