# Generated by Django 5.0.7 on 2024-09-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0004_activeproblem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeproblem',
            old_name='ID',
            new_name='problem',
        ),
    ]
