# Generated by Django 5.0.7 on 2024-09-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0005_rename_id_activeproblem_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='date_joined',
            new_name='start_date',
        ),
    ]
