# Generated by Django 4.2.16 on 2024-10-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0006_rename_date_joined_problem_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(),
        ),
    ]
